// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Fallback keeps `prisma generate` working in CI/Vercel even before
    // DATABASE_URL is configured; the real URL is injected at runtime.
    url: process.env["DATABASE_URL"] ?? "postgresql://placeholder:x@localhost/placeholder",
  },
});
